# Generated by Django 4.2.27 on 2026-01-02 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('block', 'Блокировка'), ('unblock', 'Разблокировка'), ('password_reset', 'Сброс пароля'), ('role_change', 'Изменение роли'), ('login', 'Вход в систему'), ('logout', 'Выход из системы')], max_length=20, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL, verbose_name='Выполнено пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог активности пользователя',
                'verbose_name_plural': 'Логи активности пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_3c3f09_idx'), models.Index(fields=['action_type', '-created_at'], name='accounts_us_action__9b8bb9_idx')],
            },
        ),
    ]
