# Generated by Django 5.0.1 on 2026-01-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivitylog'),
        ('regions', '0006_region_polygon_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_rate', models.FloatField(default=1.0, help_text='Вероятность принятия предложения (0.0-1.0)', verbose_name='Acceptance Rate')),
                ('cancel_rate', models.FloatField(default=0.0, help_text='Вероятность отмены после принятия (0.0-1.0)', verbose_name='Cancel Rate')),
                ('offers_last_60min', models.IntegerField(default=0, verbose_name='Офферов за последний час')),
                ('orders_last_60min', models.IntegerField(default=0, verbose_name='Заказов за последний час')),
                ('rejections_count', models.IntegerField(default=0, verbose_name='Количество отклонений')),
                ('cancellations_count', models.IntegerField(default=0, verbose_name='Количество отмен')),
                ('no_shows_count', models.IntegerField(default=0, verbose_name='Количество no-show')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Статистика водителя',
                'verbose_name_plural': 'Статистика водителей',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='idle_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Свободен с'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('offline', 'Офлайн'), ('online_idle', 'Онлайн, свободен'), ('offered', 'Получил предложение'), ('enroute_to_pickup', 'Едет к подаче'), ('on_trip', 'В поездке'), ('paused', 'Перерыв/блокировка')], default='offline', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status', 'is_online'], name='accounts_dr_status_0f4b41_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['region', 'status'], name='accounts_dr_region__ba4f68_idx'),
        ),
        migrations.AddField(
            model_name='driverstatistics',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='accounts.driver', verbose_name='Водитель'),
        ),
    ]
