# Generated by Django 5.0.1 on 2026-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID региона')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('center_lat', models.FloatField(verbose_name='Широта центра')),
                ('center_lon', models.FloatField(verbose_name='Долгота центра')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['title'],
            },
        ),
    ]
