# Generated by Django 4.2.27 on 2026-01-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID города')),
                ('title', models.CharField(max_length=100, verbose_name='Название города')),
                ('center_lat', models.FloatField(verbose_name='Широта центра')),
                ('center_lon', models.FloatField(verbose_name='Долгота центра')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['city', 'title'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='regions.city', verbose_name='Город'),
        ),
    ]
