# Generated by Django 4.2.27 on 2026-01-02 19:16

from django.db import migrations


def populate_city_for_regions(apps, schema_editor):
    """Создает город Атырау и связывает все существующие регионы с ним"""
    City = apps.get_model('regions', 'City')
    Region = apps.get_model('regions', 'Region')
    
    # Создаем город Атырау
    atyrau_city, created = City.objects.get_or_create(
        id='atyrau',
        defaults={
            'title': 'Атырау',
            'center_lat': 47.1067,
            'center_lon': 51.9167
        }
    )
    
    # Связываем все регионы без города с Атырау
    Region.objects.filter(city__isnull=True).update(city=atyrau_city)


def reverse_populate_city_for_regions(apps, schema_editor):
    """Откат миграции - удаляет связь регионов с городом"""
    Region = apps.get_model('regions', 'Region')
    Region.objects.all().update(city=None)


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_city_alter_region_options_region_city'),
    ]

    operations = [
        migrations.RunPython(populate_city_for_regions, reverse_populate_city_for_regions),
    ]
