# Generated by Django 4.2.27 on 2026-01-02 19:17

from django.db import migrations, models
import django.db.models.deletion


def ensure_all_regions_have_city(apps, schema_editor):
    """Убеждаемся, что все регионы имеют город"""
    City = apps.get_model('regions', 'City')
    Region = apps.get_model('regions', 'Region')
    
    # Получаем или создаем город Атырау
    atyrau_city, _ = City.objects.get_or_create(
        id='atyrau',
        defaults={
            'title': 'Атырау',
            'center_lat': 47.1067,
            'center_lon': 51.9167
        }
    )
    
    # Связываем все регионы без города с Атырау
    Region.objects.filter(city__isnull=True).update(city=atyrau_city)


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_populate_city_for_regions'),
    ]

    operations = [
        migrations.RunPython(ensure_all_regions_have_city),
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='regions',
                to='regions.city',
                verbose_name='Город'
            ),
        ),
    ]
