# Generated by Django 4.2.27 on 2026-01-02 19:20

from django.db import migrations


def update_atyrau_coordinates(apps, schema_editor):
    """Обновляет координаты города Атырау и его регионов"""
    City = apps.get_model('regions', 'City')
    Region = apps.get_model('regions', 'Region')
    
    # Обновляем координаты города Атырау
    try:
        atyrau_city = City.objects.get(id='atyrau')
        atyrau_city.center_lat = 55.7558
        atyrau_city.center_lon = 37.6173
        atyrau_city.save()
    except City.DoesNotExist:
        # Если города нет, создаем его
        City.objects.create(
            id='atyrau',
            title='Атырау',
            center_lat=55.7558,
            center_lon=37.6173
        )
    
    # Обновляем координаты регионов
    regions_updates = {
        'atyrau_center': {'center_lat': 55.7558, 'center_lon': 37.6173},
        'atyrau_north': {'center_lat': 55.8, 'center_lon': 37.6},
        'atyrau_south': {'center_lat': 55.6, 'center_lon': 37.6},
        'atyrau_east': {'center_lat': 55.75, 'center_lon': 37.7},
        'atyrau_west': {'center_lat': 55.75, 'center_lon': 37.5},
    }
    
    for region_id, coords in regions_updates.items():
        try:
            region = Region.objects.get(id=region_id)
            region.center_lat = coords['center_lat']
            region.center_lon = coords['center_lon']
            region.save()
        except Region.DoesNotExist:
            pass  # Регион не существует, пропускаем


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_make_city_required'),
    ]

    operations = [
        migrations.RunPython(update_atyrau_coordinates),
    ]
