# Generated by Django 4.2.27 on 2026-01-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_update_atyrau_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, help_text='Массив координат [[lat, lon], ...] для границ региона', null=True, verbose_name='Координаты полигона границ'),
        ),
        migrations.AddField(
            model_name='region',
            name='service_radius_meters',
            field=models.FloatField(blank=True, help_text='Радиус обслуживания от центра региона в метрах', null=True, verbose_name='Радиус обслуживания (метры)'),
        ),
    ]
