# Generated by Django 5.0.1 on 2026-03-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0006_region_polygon_coordinates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID района",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название района"),
                ),
                ("center_lat", models.FloatField(verbose_name="Широта центра")),
                ("center_lon", models.FloatField(verbose_name="Долгота центра")),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="regions.district",
                verbose_name="Район",
            ),
        ),
    ]
