# Generated by Django 5.0.1 on 2026-01-01 18:05

import django.db.models.deletion
import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('pickup_title', models.CharField(max_length=500, verbose_name='Адрес отправления')),
                ('dropoff_title', models.CharField(max_length=500, verbose_name='Адрес назначения')),
                ('pickup_lat', models.FloatField(verbose_name='Широта отправления')),
                ('pickup_lon', models.FloatField(verbose_name='Долгота отправления')),
                ('dropoff_lat', models.FloatField(verbose_name='Широта назначения')),
                ('dropoff_lon', models.FloatField(verbose_name='Долгота назначения')),
                ('desired_pickup_time', models.DateTimeField(validators=[orders.validators.validate_pickup_time], verbose_name='Желаемое время забора')),
                ('has_companion', models.BooleanField(default=False, verbose_name='С сопровождением')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('awaiting_dispatcher_decision', 'Ожидание решения диспетчера'), ('rejected', 'Отклонено'), ('active_queue', 'В очереди'), ('assigned', 'Назначено'), ('driver_en_route', 'Водитель в пути'), ('arrived_waiting', 'Ожидание пассажира'), ('no_show', 'Пассажир не пришел'), ('ride_ongoing', 'Поездка началась'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('incident', 'Инцидент')], default='draft', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Назначен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('assignment_reason', models.TextField(blank=True, null=True, verbose_name='Причина назначения')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('video_recording', models.BooleanField(blank=True, null=True, verbose_name='Видеозапись')),
                ('upload_started', models.BooleanField(blank=True, null=True, verbose_name='Загрузка начата')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.driver', verbose_name='Водитель')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус от')),
                ('status_to', models.CharField(max_length=50, verbose_name='Статус до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие заказа',
                'verbose_name_plural': 'События заказов',
                'ordering': ['-created_at'],
            },
        ),
    ]
