# Generated by Django 4.2.27 on 2026-01-02 18:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние в километрах'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предварительная цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Финальная цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_breakdown',
            field=models.JSONField(blank=True, help_text='Разбивка стоимости по компонентам', null=True, verbose_name='Детализация цены'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_time_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время ожидания в минутах'),
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за километр')),
                ('price_per_minute_waiting', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за минуту ожидания')),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальная стоимость поездки')),
                ('companion_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Доплата за сопровождение')),
                ('disability_category_multiplier', models.JSONField(default=dict, help_text='Формат: {"I группа": 1.0, "II группа": 1.0, "III группа": 1.0, "Ребенок-инвалид": 0.8}', verbose_name='Множители для категорий инвалидности')),
                ('night_time_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.2'), help_text='Применяется с 22:00 до 06:00', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Множитель для ночного времени')),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.1'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Множитель для выходных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('region', models.ForeignKey(blank=True, help_text='Если не указан, применяется ко всем регионам', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_configs', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Конфигурация ценообразования',
                'verbose_name_plural': 'Конфигурации ценообразования',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
