# Generated by Django 5.0.1 on 2026-01-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driverstatistics_driver_idle_since_driver_rating_and_more'),
        ('orders', '0002_order_distance_km_order_estimated_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название конфигурации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('eta_max_seconds', models.IntegerField(default=720, verbose_name='Максимальный ETA до подачи (секунды)')),
                ('k_candidates', models.IntegerField(default=50, verbose_name='Количество кандидатов для скоринга (Top-K)')),
                ('offer_timeout_seconds', models.IntegerField(default=15, verbose_name='Таймаут оффера (секунды)')),
                ('w_eta', models.FloatField(default=0.4, help_text='Влияние времени подачи на cost', verbose_name='Вес ETA')),
                ('w_deadhead', models.FloatField(default=0.15, help_text='Влияние расстояния до клиента', verbose_name='Вес холостого пробега')),
                ('w_reject', models.FloatField(default=0.2, help_text='Штраф за вероятность отклонения', verbose_name='Вес риска отказа')),
                ('w_cancel', models.FloatField(default=0.15, help_text='Штраф за вероятность отмены', verbose_name='Вес риска отмены')),
                ('w_fairness', models.FloatField(default=0.05, help_text='Баланс распределения заказов', verbose_name='Вес справедливости')),
                ('w_zone', models.FloatField(default=0.03, help_text='Штраф за вытягивание из зоны спроса', verbose_name='Вес баланса зон')),
                ('w_quality', models.FloatField(default=0.02, help_text='Штраф за низкий рейтинг/качество', verbose_name='Вес качества')),
                ('min_rating', models.FloatField(default=4.0, help_text='Минимальный рейтинг для принятия заказа', verbose_name='Минимальный рейтинг')),
                ('max_offers_per_hour', models.IntegerField(default=20, help_text='Лимит предложений водителю за час', verbose_name='Максимум офферов в час')),
                ('expand_search_after_seconds', models.IntegerField(default=30, help_text='Через сколько секунд увеличить радиус/ETA', verbose_name='Расширить поиск через (секунды)')),
                ('expand_eta_multiplier', models.FloatField(default=1.5, help_text='Во сколько раз увеличить максимальный ETA', verbose_name='Множитель ETA при расширении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Конфигурация распределения',
                'verbose_name_plural': 'Конфигурации распределения',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('awaiting_dispatcher_decision', 'Ожидание решения диспетчера'), ('rejected', 'Отклонено'), ('created', 'Создан'), ('matching', 'Поиск водителя'), ('active_queue', 'В очереди'), ('offered', 'Предложение отправлено'), ('assigned', 'Назначено'), ('driver_en_route', 'Водитель в пути'), ('arrived_waiting', 'Ожидание пассажира'), ('no_show', 'Пассажир не пришел'), ('ride_ongoing', 'Поездка началась'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('incident', 'Инцидент')], default='draft', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('timeout', 'Таймаут')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ получен')),
                ('eta_seconds', models.IntegerField(blank=True, null=True, verbose_name='ETA в секундах')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='Расстояние в км')),
                ('cost_score', models.FloatField(blank=True, null=True, verbose_name='Cost score')),
                ('selection_reason', models.TextField(blank=True, null=True, verbose_name='Причина выбора')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.driver', verbose_name='Водитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Предложение заказа',
                'verbose_name_plural': 'Предложения заказов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_orde_order_i_ddb3a2_idx'), models.Index(fields=['driver', 'status'], name='orders_orde_driver__f2616a_idx'), models.Index(fields=['expires_at'], name='orders_orde_expires_96a9a4_idx')],
            },
        ),
    ]
