# Generated by Django 5.0.1 on 2026-01-09 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dispatchconfig_alter_order_status_orderoffer'),
        ('regions', '0006_region_polygon_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locked_surge_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surge множитель, зафиксированный при назначении/старте поездки', max_digits=5, null=True, verbose_name='Зафиксированный surge множитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена, показанная клиенту до поездки', max_digits=10, null=True, verbose_name='Предварительная цена (Quote)'),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время расчета quote'),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_surge_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Surge множитель при расчете quote'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина изменения маршрута'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_changed',
            field=models.BooleanField(default=False, help_text='Клиент изменил маршрут (добавил точку/сменил адрес)', verbose_name='Маршрут изменен'),
        ),
        migrations.AddField(
            model_name='order',
            name='surge_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время фиксации surge'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Посадка (базовая стоимость)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Фиксированный сбор за бронирование', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сбор сервиса'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='final_price_cap_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.30'), help_text='Финальная цена не может превышать quote * этот множитель (например 1.30 = +30%)', max_digits=5, verbose_name='Лимит отклонения финальной цены'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='included_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Бесплатные километры (обычно 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Включенные километры'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='included_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Бесплатные минуты (обычно 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Включенные минуты'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='name',
            field=models.CharField(default='Econom', help_text='Например: Econom, Comfort, Business', max_length=100, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='price_per_minute',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Ставка за минуту поездки', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за минуту в движении'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='rounding_rule',
            field=models.CharField(choices=[('1', 'До 1 ₸'), ('5', 'До 5 ₸'), ('10', 'До 10 ₸'), ('50', 'До 50 ₸')], default='10', help_text='До какого значения округлять цену', max_length=10, verbose_name='Правило округления'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='surge_enabled',
            field=models.BooleanField(default=True, help_text='Разрешить динамическое изменение цены', verbose_name='Включен surge pricing'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='surge_max_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.0'), help_text='Максимальный множитель (например 3.0 = +200%)', max_digits=5, verbose_name='Максимальный множитель surge'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='surge_min_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Минимальный множитель (обычно 1.0)', max_digits=5, verbose_name='Минимальный множитель surge'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='surge_sensitivity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Коэффициент k для расчета множителя (0.3-0.7)', max_digits=5, verbose_name='Чувствительность surge'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='surge_smoothing_alpha',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.7'), help_text='Alpha для экспоненциального сглаживания (0.6-0.9)', max_digits=5, verbose_name='Коэффициент сглаживания surge'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='surge_step',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.1'), help_text='Шаг округления (например 0.1 для 1.0, 1.1, 1.2...)', max_digits=5, verbose_name='Шаг множителя surge'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='wait_free_min',
            field=models.IntegerField(default=3, help_text='Минуты бесплатного ожидания после прибытия', verbose_name='Бесплатное ожидание (минуты)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='wait_per_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Ставка за минуту ожидания после бесплатного периода', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за минуту ожидания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: используйте quote', max_digits=10, null=True, verbose_name='Предварительная цена (старое поле)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_breakdown',
            field=models.JSONField(blank=True, help_text='Разбивка стоимости по компонентам (DEPRECATED: используйте PriceBreakdown)', null=True, verbose_name='Детализация цены (старое поле)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='minimum_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальная стоимость поездки'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за километр'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='price_per_minute_waiting',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='DEPRECATED: используйте wait_per_min', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за минуту ожидания (старое поле)'),
        ),
        migrations.CreateModel(
            name='CancelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название политики')),
                ('cancel_before_assigned_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Штраф за отмену до назначения')),
                ('grace_cancel_seconds', models.IntegerField(default=120, help_text='Время после назначения, когда отмена бесплатна', verbose_name='Льготный период отмены (секунды)')),
                ('cancel_after_assigned_fee', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Штраф за отмену после назначения')),
                ('cancel_after_arrived_fee', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Штраф за отмену после прибытия')),
                ('cancel_after_arrived_include_waiting', models.BooleanField(default=True, help_text='Добавлять стоимость ожидания к штрафу', verbose_name='Включать стоимость ожидания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancel_policies', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Политика отмены',
                'verbose_name_plural': 'Политики отмены',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Посадка')),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Километры')),
                ('distance_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость за км')),
                ('duration_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Минуты')),
                ('duration_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость за минуты')),
                ('waiting_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Минуты ожидания')),
                ('waiting_free_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Бесплатные минуты')),
                ('waiting_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость ожидания')),
                ('booking_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сбор сервиса')),
                ('companion_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Доплата за сопровождение')),
                ('zone_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Зональные сборы')),
                ('toll_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Платные дороги')),
                ('options_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Дополнительные опции')),
                ('night_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Множитель ночного времени')),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Множитель выходных')),
                ('disability_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Множитель категории инвалидности')),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Множитель surge')),
                ('surge_applied_to', models.CharField(choices=[('all', 'Вся сумма'), ('ride_only', 'Только поездка (без сборов)')], default='all', max_length=20, verbose_name='К чему применяется surge')),
                ('subtotal_before_surge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Промежуточная сумма до surge')),
                ('subtotal_after_surge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Промежуточная сумма после surge')),
                ('minimum_fare_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Доплата до минимума')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Итоговая сумма')),
                ('rounding_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Округление')),
                ('price_type', models.CharField(choices=[('quote', 'Предварительная (Quote)'), ('final', 'Финальная (Final)')], default='quote', max_length=20, verbose_name='Тип цены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_breakdown_detail', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Детализация цены',
                'verbose_name_plural': 'Детализации цен',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('center_lat', models.FloatField(verbose_name='Широта центра')),
                ('center_lon', models.FloatField(verbose_name='Долгота центра')),
                ('radius_meters', models.FloatField(blank=True, help_text='Если указан, зона - круг. Иначе используется polygon_coordinates', null=True, verbose_name='Радиус (метры)')),
                ('polygon_coordinates', models.JSONField(blank=True, help_text='Массив координат [[lat, lon], ...] для границ зоны', null=True, verbose_name='Координаты полигона')),
                ('current_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Текущий множитель surge')),
                ('smoothed_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Сглаженный множитель surge')),
                ('demand_count', models.IntegerField(default=0, verbose_name='Спрос (запросы за 5 мин)')),
                ('supply_count', models.IntegerField(default=0, verbose_name='Предложение (доступные водители)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surge_zones', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Зона surge pricing',
                'verbose_name_plural': 'Зоны surge pricing',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['region', 'is_active'], name='orders_surg_region__731bae_idx'), models.Index(fields=['last_updated'], name='orders_surg_last_up_e4357b_idx')],
            },
        ),
    ]
