# Generated by Django 4.2.27 on 2026-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_locked_surge_multiplier_order_quote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dropoff_object_name",
            field=models.CharField(
                blank=True,
                help_text='Обязательное поле для диспетчера: например "Поликлиника 3". Карта ищет по улице, диспетчер ориентируется по названию объекта.',
                max_length=255,
                null=True,
                verbose_name="Название объекта (куда)",
            ),
        ),
    ]
