# Generated by Django 4.2.27 on 2026-03-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_add_dropoff_object_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_object_name",
            field=models.CharField(
                blank=True,
                help_text='Обязательное поле для диспетчера: например "Дом инвалида", "Поликлиника 3". Карта ищет по улице, диспетчер ориентируется по названию объекта.',
                max_length=255,
                null=True,
                verbose_name="Название объекта (откуда)",
            ),
        ),
    ]
