# Generated by Django 5.0.1 on 2026-03-05 02:21

from django.db import migrations, models


def set_wait_free_min_20(apps, schema_editor):
    PricingConfig = apps.get_model("orders", "PricingConfig")
    PricingConfig.objects.filter(wait_free_min__lt=20).update(wait_free_min=20)


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_add_pickup_object_name"),
    ]

    operations = [
        migrations.RunPython(set_wait_free_min_20, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pricingconfig",
            name="wait_free_min",
            field=models.IntegerField(
                default=20,
                help_text="Минуты бесплатного ожидания после прибытия (сверх — платно)",
                verbose_name="Бесплатное ожидание (минуты)",
            ),
        ),
    ]
