# Generated by Django 5.0.1 on 2026-03-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_wait_free_min_20"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchconfig",
            name="max_deadhead_km",
            field=models.FloatField(
                blank=True,
                default=20.0,
                help_text="Не назначать заказы, если водитель дальше (0 = без ограничения)",
                null=True,
                verbose_name="Максимальный холостой пробег (км)",
            ),
        ),
    ]
