# Generated by Django 5.0.1 on 2026-03-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_add_max_deadhead_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchconfig",
            name="fairness_scale",
            field=models.FloatField(
                default=2.0,
                help_text="Разница в заказах для полного штрафа (2 = чувствительнее)",
                verbose_name="Масштаб fairness",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchconfig",
            name="w_fairness",
            field=models.FloatField(
                default=0.15,
                help_text="Баланс распределения заказов",
                verbose_name="Вес справедливости",
            ),
        ),
    ]
